### ISSUE TITLE
Template language - add handlebars support

### ISSUE THREAD

**Issue by molinto** [rschmukler/powerdrill#13]
Great module, very impressive work :)

Suggestion really:
On the mandrill-api nodejs, the ability to use handlebars template {{ name }} is possible, eg:
https://bitbucket.org/mailchimp/mandrill-api-node/src/cce9b2efe8cf71f0fb7d7a97723a2edc7e40b236/mandrill.js?at=master&fileviewer=file-view-default#mandrill.js-1198

merge_language tag - "the merge tag language to use when evaluating merge tags, either mailchimp or handlebars oneof(mailchimp, handlebars)":
https://mandrillapp.com/api/docs/messages.nodejs.html#method=send-template

Sharry

**Comment by manuel-reil** [comment]
+1
